[app]
name = "Micro Servico  - BLog Wordpress"
generateDB = true
cron = "@every 1m"
url_wordpress  = "http://localhost"
url_public_uploads = "https://cal.com/uploads"

[database]
host = "localhost"
port = "5432"
user = "postgres"
pass = "Postgress2022!"
name = "postgres"
